backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
show_preview_links: true
search: false
site_url: "https://blog.abhin.dev"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    identifier_field: title
    label: "Blog" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["Tech", "Poetry", "Cricket", "Coffee", "Miscellaneous"]
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "date"
        format: "D MMM YYYY"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        choose_url: true
      - label: "Description"
        name: desc
        widget: "string"
      - label: "Available on"
        name: "availableOn"
        widget: "list"
        fields:
          - label: "Platform"
            name: "platform"
            widget: "string"
          - label: "Source"
            name: "src"
            widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
